# # NumPy more function

In [1]:
import numpy as np

In [2]:
arr=np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b=np.array([1,3,6,54,45,9,64,87,2,31,20,85,13,465,65,231,25,90])
#b=b.reshape(6,3)# reshape dimention

In [5]:
np.argsort(b) # the index which sort the array

array([ 0,  8,  1,  2,  5, 12, 10, 16,  9,  4,  3,  6, 14, 11,  7, 17, 15,
       13], dtype=int64)

In [6]:
np.argmin(b) # min element index of array

0

In [7]:
np.argmax(b) # max element index in array

13

In [8]:
c=np.array([1,6,5,48,95,65,78,23,64,200,100,60,89,54,63,70,75,81])

In [9]:
c=c.reshape(6,3)

In [10]:
c

array([[  1,   6,   5],
       [ 48,  95,  65],
       [ 78,  23,  64],
       [200, 100,  60],
       [ 89,  54,  63],
       [ 70,  75,  81]])

In [11]:
#np.argsort(c)

In [12]:
np.argsort(c,axis=0)

array([[0, 0, 0],
       [1, 2, 3],
       [5, 4, 4],
       [2, 5, 2],
       [4, 1, 1],
       [3, 3, 5]], dtype=int64)

In [13]:
np.argsort(c,axis=1)

array([[0, 2, 1],
       [0, 2, 1],
       [1, 2, 0],
       [2, 1, 0],
       [1, 2, 0],
       [0, 1, 2]], dtype=int64)

In [14]:
np.argmin(c)

0

In [15]:
np.argmax(c)

9