# # Axis, sorting and Useful Num function

In [1]:
import numpy as np

In [2]:
arr1=np.array([[1,2,3],[4,5,6]])

In [3]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr1.sum(axis=1) #axis can sum of 1st rows

array([ 6, 15])

In [5]:
arr1.sum(axis=0) #axis the data by column

array([5, 7, 9])

In [6]:
b=np.array([[8,3,4],[7,8,6]])

In [7]:
a=np.array([[1,2,3],[4,5,6]])

In [13]:
np.dot(a,b.transpose())

array([[ 26,  41],
       [ 71, 104]])

In [11]:
len(dir(np))

618

In [12]:
np.cross(a,b)

array([[ -1,  20, -13],
       [-18,  18,  -3]])

In [14]:
arr2=np.array([[13,95,10],[3,12,5]])

In [15]:
np.sort(arr2)

array([[10, 13, 95],
       [ 3,  5, 12]])

In [19]:
%%time
np.sort(arr2, axis=0)

Wall time: 0 ns


array([[ 3, 12,  5],
       [13, 95, 10]])

In [20]:
%%time
np.sort(arr2, axis=0, kind='mergesort')

Wall time: 0 ns


array([[ 3, 12,  5],
       [13, 95, 10]])

In [21]:
%%time
np.sort(arr2, axis=0, kind='heapsort')

Wall time: 96 ms


array([[ 3, 12,  5],
       [13, 95, 10]])

In [22]:
%%time
np.sort(arr2, axis=0, kind='quicksort')

Wall time: 0 ns


array([[ 3, 12,  5],
       [13, 95, 10]])

In [24]:
# %%time
# np.sort(arr2, axis=0, kind='timesort') //time sloting not possible