# # Basic NumPy Function

In [1]:
import numpy as np

In [2]:
array1=np.array([[3,4,5,9,8],[6,3,4,7,6]])

In [3]:
print(array1)

[[3 4 5 9 8]
 [6 3 4 7 6]]


In [4]:
print(type(array1))

<class 'numpy.ndarray'>


In [5]:
array1.shape



(2, 5)

In [6]:
array1.dtype

dtype('int32')

In [7]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [9]:
np.empty((4,5))

array([[1.24266582e-311, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000, 1.24136754e-311],
       [5.30276956e+180, 1.57076922e-076, 6.98341640e-076,
        4.86528653e-086, 3.35559922e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180,
        3.94356143e+180, 3.50609475e-033],
       [8.38584389e+169, 8.96786849e-067, 6.81768807e-067,
        4.71010071e-143, 1.50008929e+248]])

# # Mathematical operation

In [10]:
array1

array([[3, 4, 5, 9, 8],
       [6, 3, 4, 7, 6]])

In [11]:
array1*array1

array([[ 9, 16, 25, 81, 64],
       [36,  9, 16, 49, 36]])

In [12]:
array1-array1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [13]:
array1**array1

array([[       27,       256,      3125, 387420489,  16777216],
       [    46656,        27,       256,    823543,     46656]],
      dtype=int32)

In [14]:
array1/array1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# # Slicing Operation

In [15]:
array2=np.array([5,4,3,2,1,7,6])

In [16]:
arr=array2[4:6].copy() #not affecting the main copy of array

In [17]:
arr[0]=9 #slicing arr[0] replace by 9

In [18]:
array2

array([5, 4, 3, 2, 1, 7, 6])

In [19]:
arr

array([9, 7])